---
# defaults file for PacketCapture

state: present
packetCaptureNamespace: packet-capture

tcpdump:
  interface: eth0
  duration: 600   # Time for each tcpdump to run in seconds 
  filepath: /tmp



restartPolicy: OnFailure
backoffLimit: 5

# List of pod names and the nodes they are deployed to
# The list is used in create_jobs
pods: [] 
