---
- hosts: localhost
  collections:
    - cloud.common
    - community.kubernetes
    - kubernetes.core
    - ioperator_sdk.util
  vars:
    targetNamespace: openshift-gitops
    targetDeployment: openshift-gitops-server
    duration: "30"
  roles:
    - packetcapture
