---
- hosts: localhost
  collections:
    - cloud.common
    - community.kubernetes
    - kubernetes.core
    - ioperator_sdk.util
  vars:
    jobId: "{{ lookup('community.general.random_string', length=4, numbers=false, special=false, upper=false) }}"
    targetNamespace: openshift-gitops
    targetDeployment: openshift-gitops-server
    duration: "30"
  roles:
    - packetcapture
