# permissions for end users to view packetcaptures.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: packetcapture-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: packet-capture-operator
    app.kubernetes.io/part-of: packet-capture-operator
    app.kubernetes.io/managed-by: kustomize
  name: packetcapture-viewer-role
rules:
- apiGroups:
  - monitoring.openshift.tpg
  resources:
  - packetcaptures
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - monitoring.openshift.tpg
  resources:
  - packetcaptures/status
  verbs:
  - get
