---
- name: "Create ConfigMap packet-capture-{{ targetNamespace }}-{{ targetDeployment }}"
  kubernetes.core.k8s:
    definition:
      api_version: v1
      kind: ConfigMap
      metadata:
        annotations:
          "ansible.sdk.operatorframework.io/verbosity": "4"
        labels:
          app.kubernetes.io/name: packet-capture
          app.kubernetes.io/instance: "{{ targetNamespace }}-{{ targetDeployment }}"
          app.kubernetes.io/part-of: packet-capture-operator
          app.kubernetes.io/managed-by: kustomize
          app.kubernetes.io/created-by: packet-capture-operator
        name: "{{ targetNamespace }}-{{ targetDeployment }}"
        namespace: "{{ packetCaptureNamespace }}"
      data:
        namespace: "{{ targetNamespace }}"
        deployment: "{{ targetDeployment }}"
        duration: "{{ duration }}"
    state: "{{ state }}"
  ignore_errors: true