---
# tasks file for PacketCapture
- name: set ConfigMap pcap-{{ namespace }}-{{ deployment }} to {{ state }}
  kubernetes.core.k8s:
    definition:
      api_version: v1
      kind: ConfigMap
      metadata:
        name: "pcapt-{{ namespace }}-{{ deployment }}"
        namespace: "{{ packetCaptureNamespace }}"
      data:
        namespace: "{{ namespace }}"
        deployment: "{{ deployment }}"
        duration: "{{ duration }}"
    state: "{{ state }}"
  ignore_errors: true